quiz/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('', include("django.contrib.auth.urls")),
    path('<int:pk>/', login_required(views.QuestionsListView.as_view()), name='questionslist'),
    path('<int:pk>/question', login_required(views.QuestionView.as_view()), name='question'),
    path('<int:pk>/results/', login_required(views.ResultsView.as_view()), name='results'),
    path('<int:question_id>/selection/', views.selection, name='selection'),
    path("register/", views.register, name="register"),
    path("about/", views.about, name="about")

]

quizz_setup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('quiz.urls')),
    path('admin/', admin.site.urls),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

"""
Db for holding Subjects
"""


class Subject(models.Model):
    subject_name = models.CharField(max_length=75, default='Extras')
    description = models.CharField(max_length=2000, default='')

    def __str__(self):
        return 'Subject name: ' + self.subject_name


"""
Db for holding Profile Info
"""


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150)
    points_scored = models.IntegerField(default=0)
    questions_attempted = models.CharField(max_length=2000, default='')
    bio = models.TextField()

    def __str__(self):
        return self.user.username + ' Points Scored: ' + \
               str(self.points_scored) + ' Questions Attempted: ' + \
               self.questions_attempted


@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


"""
Db for holding Question
"""


class Question(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=300)
    timeout = models.IntegerField(default=75)
    points = models.IntegerField(default=1)

    def __str__(self):
        """
        Function for representing the question in correct format
        :return: str object
        """
        return 'Question: ' + self.question_text + \
               ' \nTimeout (seconds):' + str(self.timeout) + \
               ' \nPoints :' + str(self.points)


"""
Db for holding Answers and Options
"""


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    option1 = models.CharField(max_length=200)
    option2 = models.CharField(max_length=200)
    option3 = models.CharField(max_length=200)
    option4 = models.CharField(max_length=200)
    correct_option = models.CharField(max_length=200)

    def __str__(self):
        """
        Function for representing the question in correct format
        :return: str object
        """
        return 'Option 1: ' + self.option1 + ' \nOption 2: ' + \
               self.option2 + ' \nOption 3: ' + self.option3 + \
               ' \nOption 4: ' + self.option4 + \
               ' \nAnswer: ' + self.correct_option

quiz/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

quiz/views.py
import re
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth import login, logout
from .models import Question, Answer, User, Subject
from .forms import RegisterForm


def filterCharacter(character):
    """
    Method to used by filter method to remove characters
    """
    if character == '':
        return False
    if character == ' ':
        return False
    else:
        return True


"""
Class used for rendering the questions pages.
Templates: questionslist.html
"""


class QuestionsListView(generic.ListView):
    template_name = 'quiz/questionslist.html'
    model = Question
    context_object_name = 'latest_question_list'

    # @login_required(login_url="/quiz/login")
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        """
        queryset for retrieveing data from DB based on PK
        :return:
        """
        subject = get_object_or_404(Subject, pk=self.kwargs['pk'])
        questions = subject.question_set.all()
        question_list = [int(s) for s in
                         filter(filterCharacter,
                                self.request.user.profile.questions_attempted.split(','))]
        for id in question_list:
            questions = questions.exclude(pk=id)
        return questions.order_by('timeout')

    def get_context_data(self, **kwargs):
        """
        Add another object as a context
        """
        context = super().get_context_data(**kwargs)
        context['subject'] = get_object_or_404(Subject, pk=self.kwargs['pk'])
        return context


"""
Class used for rendering the Home page.
Templates: index.html
"""


class IndexView(generic.ListView):
    template_name = 'quiz/index.html'
    context_object_name = 'subjects'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['user'] = 'Hi ' + self.request.user.username
            context['register'] = 'Sign Out'
        else:
            context['user'] = 'Signin'
            context['register'] = 'Register'
        return context

    def get_queryset(self):
        return Subject.objects.all()


"""
Class used for rendering the question page.
Templates: question.html
"""


class QuestionView(generic.DetailView):
    model = Question
    template_name = 'quiz/question.html'

    # @login_required(login_url="/quiz/login")
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Add extra info as a context
        """
        context = super().get_context_data(**kwargs)
        question = get_object_or_404(Question, pk=self.object.pk)
        question_info = question.answer_set.all()
        option_set = []
        for options in question_info:
            option_set.append(options.option1)
            option_set.append(options.option2)
            option_set.append(options.option3)
            option_set.append(options.option4)
        context['option_set'] = option_set
        context['points_allocated'] = question.points
        return context


"""
Class used for rendering the results page.
Templates: results.html
"""


class ResultsView(generic.DetailView):
    model = User
    template_name = 'quiz/results.html'
    message = ''
    subject_id = ''

    def get(self, request, *args, **kwargs):
        if len(self.request.GET) > 0:
            self.message = self.request.GET['message']
            self.subject_id = self.request.GET['subjectid']
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = self.message
        context['subject_id'] = self.subject_id
        return context


@login_required(login_url="/login")
def selection(request, question_id):
    """
    Verification of selected answer.
    Improvements: Points stored in session instead of DB
    :param request:
    :param question_id: pk for questions
    :return:
    """
    regex_query = re.compile("([a-zA-Z ]+)([0-9]+)")
    question = get_object_or_404(Question, pk=question_id)
    if request.user.is_authenticated:
        user = request.user
    question_info = question.answer_set.all()
    option_set = []
    for options in question_info:
        option_set.append(options.option1)
        option_set.append(options.option2)
        option_set.append(options.option3)
        option_set.append(options.option4)
    try:
        correct_option = question_info[0].correct_option
        correct_option = int(regex_query.match(correct_option).groups()[1])
        if len(request.POST) > 1:
            selected = request.POST['selection']
        else:
            selected = ' '
    except (KeyError, Answer.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'quiz/404.html', {
            'question': question,
            'error_message': "Answer is not saved correct by Admin. "
                             "Contact technical support.",
        })
    except:
        return render(request, 'quiz/404.html',
                      {'question': question,
                       'error_message': "Answer is "
                                        "not saved "
                                        "correct "
                                        "by Admin. "
                                        "Contact "
                                        "technical "
                                        "support.",
                       })
    else:
        if selected == " ":
            message = "Correct Answer is " \
                      + str(option_set[correct_option - 1])
        elif selected == str(correct_option):
            user.profile.points_scored += int(question.points)
            message = "Correct Answer."
        else:
            message = "Incorrect. Correct Answer is " \
                      + str(option_set[correct_option - 1])
        user.profile.questions_attempted += str(question_id) + ', '
        user.save()
        return HttpResponseRedirect(
            reverse('quiz:results',
                    kwargs={'pk': user.pk}) + '?message=' + message +
            '&' + 'subjectid=' + str(question.subject_id))


def logout_view(request):
    logout(request)


def register(request):
    """
    Method used for rendering the register page.
    Templates: register.html
    """
    user = None
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
        else:
            return render(request, "quiz/register.html", {"form": form})
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        login(request, user)
        return redirect("/")
    else:
        form = RegisterForm()
        return render(request, "quiz/register.html", {"form": form})


def about(request):
    return render(request, 'quiz/about.html');

quiz/templates/quiz/about.html
<!doctype html>
<html>
<head>
    {% load static %}
    <link href="{% static '/quiz/css/qstyle.css' %}" rel="stylesheet">
</head>
<body class="bod">


<div id="rotate-words">
    <div>Welcome to Game of Facts<br/> <span>Everyone</span></div>
    <div>A simple quiz created for<br/> <span>Middle-schoolers</span></div>
    <div>For improving knowledge for <br/> <span>For Everyone</span></div>
    <div>This website is created by<br/> <span>Django</span></div>
    <div>With special effects from full-page.js<br/> <span> </span></div>
    <div>Other effects created using<br/> <span>CSS</span></div>
    <div>Thanks keith counter timer for<br/> <span>Jquery timer </span></div>

</div>


</body>
</html>

quiz/templates/quiz/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}| Game of Facts{% endblock %}</title>

    {% block headcontent %}{% endblock %}

    <link rel="stylesheet" href="{% static 'quiz/css/qstyle.css' %}" type="text/css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
            integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
            integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
            crossorigin="anonymous"></script>

    {% block headcontent_end %}{% endblock %}

</head>

<body>

{% include "quiz/navbar.html" %}

{% block content %} {% endblock %}


</body>

</html>

quiz/templates/quiz/index.html
<!DOCTYPE html>
<html lang="en">


<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="{% static '/quiz/css/fullpage.min.css' %}">
    <link rel="stylesheet" href="{% static '/quiz/css/style.css' %}">
    <!-- <link rel="stylesheet" href="../../static/quiz/css/bootstrap.css"> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <title>Game of Facts</title>
</head>

<body>


<!-- Modal Start -->


<div class="modal fade bd-example-modal-sm" id="popup" tabindex="99" role="dialog" aria-labelledby="mySmallModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div id="jumpto" class="nav-links">

                <a class="nav-link">Science</a>
                <a class="nav-link">Math</a>
                <a class="nav-link">English</a>
                <a class="nav-link">Humanities</a>
            </div>
            <!-- Modal End -->
        </div>
    </div>
</div>


<div id="header">
    <div class="logo-container">

        <img src="{% static 'quiz/img/profile.png' %}" alt="logo"/>


    </div>
    <nav>
        <ul class="nav-links">

            <li><a class="nav-link" href="{% url 'quiz:login' %}">{{ user }}</a></li>
            {% if register == 'Register' %}
                <li><a class="nav-link" href="{% url 'quiz:register' %}">{{ register }}</a></li>
            {% else %}
                <li><a class="nav-link" href="/logout">Sign Out</a></li>
            {% endif %}
            <li><a class="nav-link" href="{% url 'quiz:about' %}">About</a></li>
        </ul>
    </nav>


</div>


<div id="fullpage">


    <div class="section s0">


        <main>
            <section class="presentation">
                <div class="introduction">

                    <div class="intro-text">
                        <h1>
                            Welcome to the Game of Facts
                        </h1>
                        <p>
                            Lets have skill-test and some learning to extend your knowledge in various domains.
                        </p>
                    </div>
                    <div class="cta">
                        <button class="cta-select" onclick="start()">Get Started</button>
                        <button class="cta-add" data-toggle="modal" data-target=".bd-example-modal-sm">Jump to?</button>


                    </div>
                </div>

            </section>


        </main>


    </div>
    <div class="section science">
        <div class="presentation">
            <div class="introduction">
                <h1>Science</h1>
                <p>
                    Here we will test your knowledge in Physics, Chemistry and Biology.
                </p>


                <div class="cta">
                    {% for subject in subjects %}
                        {% if subject.subject_name == "Science" %}
                            <button class="cta-select" onClick="javascript:location.href ='/{{ subject.pk }}';">Get
                                Started
                            </button>
                        {% endif %}
                    {% endfor %}
                    <button class="cta-add" data-toggle="modal" data-target=".bd-example-modal-sm">Jump to?</button>

                </div>
            </div>
        </div>
    </div>


    <div class="section math">
        <div class="presentation">
            <div class="Introduction">
                <h1>Math</h1>
                <p>
                    Here we will test your knowledge in Linear Algebra and Logical questions.
                </p>


                <div class="cta">
                    {% for subject in subjects %}
                        {% if subject.subject_name == "Math" %}
                            <button class="cta-select" onClick="javascript:location.href ='/{{ subject.pk }}';">Get
                                Started
                            </button>
                        {% endif %}
                    {% endfor %}
                    <button class="cta-add" data-toggle="modal" data-target=".bd-example-modal-sm">Jump to?</button>

                </div>
            </div>


        </div>
    </div>


    <div class="section english">
        <div class="presentation">
            <div class="Introduction">
                <h1>English</h1>
                <p>
                    Here we will test your knowledge in Literature.
                </p>

                <div class="cta">
                    {% for subject in subjects %}
                        {% if subject.subject_name == "English" %}
                            <button class="cta-select" onClick="javascript:location.href ='/{{ subject.pk }}';">Get
                                Started
                            </button>
                        {% endif %}
                    {% endfor %}
                    <button class="cta-add" data-toggle="modal" data-target=".bd-example-modal-sm">Jump to?</button>

                </div>
            </div>

        </div>
    </div>
    <div class="section humanities">
        <div class="presentation">
            <div class="Introduction">
                <h1>Humanities</h1>
                <p>
                    Here we will test your knowledge in Social Sciences.
                </p>


                <div class="cta">
                    {% for subject in subjects %}
                        {% if subject.subject_name == "Humanities" %}
                            <button class="cta-select" onClick="javascript:location.href ='/{{ subject.pk }}';">Get
                                Started
                            </button>
                        {% endif %}
                    {% endfor %}
                    <button class="cta-add" data-toggle="modal" data-target=".bd-example-modal-sm">Jump to?</button>

                </div>
            </div>

        </div>
    </div>


</div>


<script src="{% static 'quiz/js/fullpage.min.js' %}"></script>
<!-- <script src="../../static/quiz/js/bootstrap.js"></script> -->

<script src="{% static 'quiz/js/custom.js' %}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<!-- <script src="./../static/quiz/js/fullpage.extensions.min.js"></script> -->

</body>

</html>

quiz/templates/quiz/navbar.html
<nav class="navbar navbar-expand-lg  bg-dark">

    <a class="navbar-brand" href="/">Game of Facts</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/{{ user.id }}/results">Results</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
{#                        <a class="dropdown-item" href="/{{ user.id }}/">Profile</a>#}
                        <a class="dropdown-item" href="/logout">Log out</a>
                        {% if user.is_superuser %}
                            <a class="dropdown-item" href="/admin">Admin</a>
                        {% endif %}
                    </div>
                    {% else %}
                <li class="nav-item"><a class="nav-link" href="/login">Log in</a></li>
                <li class="nav-item"><a class="nav-link" href="/register">Sign up</a></li>
            {% endif %}
        </ul>

    </div>

</nav>
</nav>

quiz/templates/quiz/question.html
<body>

{% extends "quiz/base.html" %}
{% load static %}

{% block title %}Game of Facts {{ block.super }}{% endblock %}

{% block content %}
    <div class="container-q">

        {% with page_title="Quiz" %}

        {% endwith %}

        <div id="countdown"></div>
        <div id="timer" value={{ question.timeout }}></div>
        <div class="quest">
            <h1>{{ question.question_text }}</h1>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
            <form id="form" action="{% url 'quiz:selection' question.pk %}" method="post">
                {% csrf_token %}
                {% for option in option_set %}
                    <input type="radio" name="selection" id="select{{ forloop.counter }}"
                           value="{{ forloop.counter }}">
                    <label for="select{{ forloop.counter }}">{{ option }}</label><br>
                {% endfor %}
                <input type="submit" class="btn btn-danger" value="Submit">
            </form>
        </div>
        <script>
            $(function () {
                var shortly = new Date();
                // alert(""+shortly.getFullYear());
                shortly.setSeconds(shortly.getSeconds() + {{ question.timeout}});

                $('#countdown').countdown({
                    until: shortly,
                    onExpiry: liftOff,
                    //,expiryUrl:"{% url 'quiz:selection' question.pk %}"
                    onTick: watchCountdown

                });
            });

            function watchCountdown(periods) {
                $('#countdown').css({"background-color": "lightblue", height: 80, 'font-size': '16pt'});
                if (periods[6] < 5) {
                    $('#countdown').css("background-color", "red");
                }
            };


            function liftOff() {

                alert("Time's Up. Your selection is saved");
                var selected = " ";
                if ($('form input[type=radio]:checked').length > 0) {
                    selection = $('form input[type=radio]:checked')[0].value
                }

                $.ajax({
                    url: "{% url 'quiz:selection' question.pk %}",
                    data: {
                        selection: selected,
                        csrfmiddlewaretoken: $('input[name="csrfmiddlewaretoken"]').val(),
                    }, type: "POST",
                    success: function (data) {
                        $("body").html(data)
                    }
                });


            }
        </script>
        <script type="text/javascript"
                src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

        <link rel="stylesheet" type="text/css" href="{% static 'quiz/css/jquery.countdown.css' %}">
        <script type="text/javascript" src="{% static 'quiz/js/jquery.plugin.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'quiz/js/jquery.countdown.min.js' %}"></script>

    </div>

{% endblock %}

quiz/templates/quiz/questionslist.html
{% extends "quiz/base.html" %}

{% block title %}Questions {{ block.super }}{% endblock %}

{% block content %}
    <div class="container">

        {% with page_title="Game of Facts" %}

        {% endwith %}

        <div class="subject-title">
            <div class="focus" data-focus="{{ subject.subject_name }}">
                <div class="focus--mask">
                    <div class="focus--mask-inner">{{ subject.subject_name }}</div>
                </div>
            </div>
        </div>

        <div class="quiz-info">
            <p class="quiz-info"> Given below are the questions with points assigned to them.</p>
            <p class="quiz-info">When you click on the question, a timer with start for that question
                with four options to select the answer.
            </p>
            <p class="quiz-info">Please note you get a single opportunity to answer the question. After opening the
                link the question is removed.
            </p>
        </div>


        {% if latest_question_list %}
            <ol style="color: white">
                {% for question in latest_question_list %}
                    <li><a class="btn btn-outline-light" href=" {% url 'quiz:question'  question.pk %}"> Question
                        with {{ question.points }} points</a></li>

                {% endfor %}
            </ol>
        {% else %}
            <p>No questions are available.</p>
        {% endif %}
    </div>


{% endblock %}

quiz/templates/quiz/register.html
{% extends "quiz/base.html" %}

{% load static %}


{% block title %}Create an Account{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
    <style>
        input {
            max-width: 20em
        }

        .fon {
            color: white
        }

    </style>
    <div clas="box large-row-spacer fon">
        <form method="POST" class="form-group large-row-spacer bg-white text-dark">
            {% csrf_token %}
            {{ form|crispy }}

            <button type="submit" class="btn btn-success">Register</button>
        </form>
    </div>
{% endblock %}

quiz/templates/quiz/results.html
{% extends "quiz/base.html" %}

{% block title %}Questions {{ block.super }}{% endblock %}

{% block content %}
    <h2 class="msg btn-outline-danger">{{ message }}</h2>
    <div class="result">
        <h1 class="res"> Results</h1>

        <h3>Name: {{ user.username }}</h3>
        <h3>Score: {{ user.profile.points_scored }}</h3>
        <h4> Questions attempted: {{ user.profile.questions_attempted }}</h4>
        <div class="redirect">
            <a class="redirect btn btn-primary" href="/{{ subject_id }}">Continue?</a>
            <a class="redirect btn btn-primary" href="{% url 'quiz:index' %} ">Pick another Subject?</a>

        </div>
    </div>
{% endblock %}